PW-4836 Store card after 3DS
Adyen/adyen-salesforce-b2b-commerce pull request #34
Opened 2021-06-15 14:52 UTC by maassenbas

## Summary
When shopper selects "save card", store payment method after 3DS1 and 3DS2 transactions. 
Place order after 3DS transactions.

## Tested scenarios

**Fixed issue**:

2021-06-16 07:51 UTC, wboereboom requested changes

2021-06-16 07:51 UTC, wboereboom commented on force-app/main/default/classes/AdyenController.cls
> +    public static String handleOnAdditionalDetails(String stateData, String storefrontName){
Consider splitting this function / breaking out some of the functionality to make it easier to read.

2021-06-16 07:51 UTC, wboereboom commented on force-app/main/default/classes/AdyenController.cls
> +    public static String handleOnAdditionalDetails(String stateData, String storefrontName){
All names used for variables are clear to me, it's just hard to wrap your head around at first glance

2021-06-16 07:51 UTC, wboereboom commented on force-app/main/default/classes/AdyenReturn.cls
> +        //TODOBAS add Payment Failed error message
Should this not be part of the feature? Or is that too much for this PR?

2021-06-16 07:51 UTC, wboereboom commented on force-app/main/default/classes/PmtAdyenPayController.cls
> +    global static String handleOnAdditionalDetails(ccrz.cc_RemoteActionContext ctx, String details){
Duplicated from PmtAdyenNewController.cls.
can it be deduped?

2021-06-16 07:51 UTC, wboereboom commented on force-app/main/default/staticresources/adyenCheckout.js
> +    let controllerAction = 'PmtAdyenPayController.handleOnAdditionalDetails';
This might be resolved using a tenary operator as well. Does it matter which one gets selected? Code looks similar (see comments above)

2021-06-16 12:58 UTC, maassenbas commented on force-app/main/default/staticresources/adyenCheckout.js
> +    let controllerAction = 'PmtAdyenPayController.handleOnAdditionalDetails';
@wboereboom ternary operator is a good idea, will update it. It does matter which one is selected based on which template is rendered.

2021-06-16 12:59 UTC, maassenbas commented on force-app/main/default/classes/PmtAdyenPayController.cls
> +    global static String handleOnAdditionalDetails(ccrz.cc_RemoteActionContext ctx, String details){
Yes, will have two "handleOnAdditionalDetails" calls in controllers PmtAdyenNewController and PmtAdyenPayController, but the logic is extracted to be handled in the AdyenController.

2021-06-16 13:00 UTC, maassenbas commented on force-app/main/default/classes/AdyenReturn.cls
> +        //TODOBAS add Payment Failed error message
This will be a separated feature. Will be too big for this PR and requires more investigation work

2021-06-16 13:01 UTC, maassenbas commented on force-app/main/default/classes/AdyenController.cls
> +    public static String handleOnAdditionalDetails(String stateData, String storefrontName){
I will try to break it down and add code comments where needed to make it more understandable.

2021-06-16 15:00 UTC, wboereboom approved these changes
🎸

2021-06-17 10:56 UTC, zaiddreakh approved these changes

2021-06-17 11:23 UTC, merged