PW-3167 State Data validator
Adyen/adyen-salesforce-b2b-commerce pull request #7
Opened 2020-11-18 10:03 UTC by maassenbas

## Summary
Deserialise the StateData into the models browserInfo, riskData, paymentMethod
This will validate the keys of the state data. 

## Tested scenarios

**Fixed issue**:

2020-11-18 11:01 UTC, maassenbas commented on force-app/main/default/staticresources/adyenCheckout.js
> +        document.getElementById('adyenStateData').value = JSON.stringify(state.data);
@cyattilakiss frontend validation will be handled in ticket PW-3064, which I'm currently implementing.

2020-11-18 11:08 UTC, maassenbas commented on force-app/main/default/classes/AdyenPaymentRequest.cls
> +                cardDetails.encryptedCardNumber = (String)paymentMethod.get('encryptedCardNumber');
I will look into this now

2020-11-18 13:50 UTC, maassenbas commented on force-app/main/default/classes/AdyenPaymentRequest.cls
> +                cardDetails.encryptedCardNumber = (String)paymentMethod.get('encryptedCardNumber');
Apparently not as easy to create a loop here and assign these values to the model. 
There is no default support for this in Apex. 
I might be able to write a helper class where I serialise it, get/set the value and deserialise it again.
But I think that is not the best solution for it for now.

2020-11-19 10:22 UTC, msilvagarcia requested changes

2020-11-19 10:22 UTC, msilvagarcia commented on force-app/main/default/classes/AdyenPaymentRequest.cls
> +            System.Debug('#### paymentType = ' + paymentType);
You can delete this one :)

2020-11-19 14:05 UTC, msilvagarcia approved these changes

2020-11-23 09:04 UTC, cyattilakiss approved these changes

2020-11-24 17:50 UTC, merged